### ISSUE TITLE
Manjaro Image Checklist For Bigscreen

### ISSUE THREAD

**Issue by AIIX** [blue-systems/plasma-bigscreen#7]
~~Latest Image: https://github.com/manjaro-arm/rpi4-images/releases/tag/bigscreen-20211129~~
~~Latest Image: https://github.com/manjaro-arm/rpi4-images/releases/tag/bigscreen-20211204~~
~~Latest Image: https://github.com/manjaro-arm/rpi4-images/releases/tag/bigscreen-20211216~~
Latest Image: https://github.com/manjaro-arm/rpi4-images/releases/tag/bigscreen-20211217

Checklist:

1. - [x] Bigscreen Shell and KCM's
2. - [x] Pico Wizard
3. - [x] kwinrc added to /home/$USER/.config for both Pico Wizard and Created user
4. - [x] Pico Wizard Bigscreen Specific Configurations 
5. - [x] Qt Virtual Keyboard with Arrow Key Navigation
6. - [x] HDMI-CEC package with Raspberry Pi 4 configuration enabled 
7. - [x] Mycroft-Core
8. - [x] Mycroft Skills / Default Voice Applications 
9. - [x] Mycroft Skill Installer
10. - [x] Pico-Wizard Mycroft Module

Needed either one of the two options below for the Raspberry Pi4 bigscreen image to be usable on 4k TV:
- [x] Auto Resolution script for Raspberry Pi 4 and other single board computers because 4K is not supported (switches to 1080p automatically on boot on 4k TV's)
- [ ] Switch the default Kernel to the latest 5.14.y Raspberry Pi 4 Kernel and add hdmi_enable_4kp60=1 to see if 4k can work (performance is unusable)

Bugs:
 - [ ] CEC works for created user when logged into bigscreen shell but not for pico-wizard as pico-wizard user is not in Video Group (requested for change to add pico-wizard to video group) 
 - [ ] Image on RPI-4 does not work with 4k resolution TV due to Hardware limitation, requires fallback to 1080p - autoResolution script pushed to image profile and works for created user only on reboot after first start, does not work for pico-wizard first boot setup - looking into fix

**Comment by AIIX** [comment]
Status: Done

~~Bigscreen list of changes for next image:~~

~~Profile Changes:~~
~~1. Replace libcec with libcec-rpi-fkms and add to build list~~
~~2. Add mycroft-bigscreen to profile and add to build list~~
~~3. Add mycroft-skill-installer to profile (it has been already added to build list)~~

~~Skel Changes:~~
~~1. Add cec-daemon.py shared on telegram chat to skel under /home/$USER/.config/autostart-scripts with execute permissions. (Attached here as well in compressed format).~~
~~[cec-daemon.tar.gz](https://github.com/blue-systems/mycroft-bigscreen-img/files/7702738/cec-daemon.tar.gz)~~

~~Package Updates:~~
~~1. Update to latest pico wizard~~
~~2. Edit Pico-Wizard pkgbuild and remove line 82~~
~~3. Edit Pico-Wizard-Bigscreen-Configs-Git pkgbuild and add the following line:
 "install -Dm644 $srcdir/$_pkgname/etc/pico-wizard/pico-wizard.conf $pkgdir/etc/pico-wizard/pico-wizard.conf"~~
~~4. Update to latest Pico-Wizard-Bigscreen-Configs-Git package~~
